---
- name: Install vim
  package:
    name: vim
    state: present

- name: Install vim config file
  copy:
    src: vimrc
    dest: '{{ ansible_env.HOME }}/.vimrc'

- name: Create Colorscheme directory
  file:
    path: '{{ ansible_env.HOME }}/.vim/colors'
    state: directory

- name: Install vim colorscheme file(s)
  copy:
    src: sublimemonokai.vim
    dest: '{{ ansible_env.HOME }}/.vim/colors/sublimemonokai.vim'
